#ifndef ENIGMA_ERRORS_H_
#define ENIGMA_ERRORS_H_

#define ENIGMA_SUCCESS 0

/* PLUGBOARD ERRORS */
#define ENIGMA_PLUGBOARD_TOO_MANY_CONNECTIONS 1
#define ENIGMA_PLUGBOARD_WRONG_CONNECTION_LENGTH 2
#define ENIGMA_PLUGBOARD_CONNECTION_NOT_ALPHA 3
#define ENIGMA_PLUGBOARD_CONNECTION_ALREADY_USED 4
#define ENIGMA_PLUGBOARD_TOO_FEW_CONNECTIONS 5

#define ENIGMA_ERROR_OUT_OF_RANGE 6

/* ROTORS ERRORS */
#define ENIGMA_ROTORS_TOO_MANY_ROTORS 7
#define ENIGMA_ROTORS_ROTOR_NAME_NOT_FOUND 8
#define ENIGMA_ROTORS_ROTOR_ALREADY_USED 9
#define ENIGMA_ROTORS_INVALID_ROTOR_POSITION 10
#define ENIGMA_ROTORS_INVALID_RING_POSITION 11
#define ENIGMA_ROTORS_TOO_FEW_ROTORS 12
#define ENIGMA_ROTORS_TOO_FEW_ROTOR_POSITIONS 13
#define ENIGMA_ROTORS_TOO_FEW_RING_POSITIONS 14

/* ENCRYPTION ERRORS */
#define ENIGMA_ENC_CHAR_NOT_ALPHA 15


#endif /* ENIGMA_ERRORS_H_ */
