#ifndef ENIGMA_ERRORS_H_
#define ENIGMA_ERRORS_H_

#define ENIGMA_SUCCESS 0

/* PLUGBOARD ERRORS */
#define ENIGMA_PLUGBOARD_TOO_MANY_CONNECTIONS 1
#define ENIGMA_PLUGBOARD_WRONG_CONNECTION_LENGTH 2
#define ENIGMA_PLUGBOARD_CONNECTION_NOT_ALPHA 3
#define ENIGMA_PLUGBOARD_CONNECTION_ALREADY_USED 4
#define ENIGMA_PLUGBOARD_TOO_FEW_CONNECTIONS 5

#define ENIGMA_ERROR_OUT_OF_RANGE 6

#endif /* ENIGMA_ERRORS_H_ */
